services:
  mongo_1:
    build: .
    image: mongocustom:8.0.1
    container_name: mongodb1
    hostname: mongodb1
    networks: [ mongonet ]
    ports: [ "27017:27017" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=rentafield
    command: --config /etc/mongod.conf --port 27017
    healthcheck:
      test: [ "CMD","mongosh", "--port", "27017" , "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo_2:
    build: .
    image: mongocustom:8.0.1
    container_name: mongodb2
    hostname: mongodb2
    networks: [ mongonet ]
    ports: [ "27018:27018" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=rentafield
    command: --config /etc/mongod.conf --port 27018
    healthcheck:
      test: [ "CMD","mongosh", "--port", "27018" , "--eval", "db.adminCommand('ping')" ]

  mongo_3:
    build: .
    image: mongocustom:8.0.1
    container_name: mongodb3
    hostname: mongodb3
    networks: [ mongonet ]
    ports: [ "27019:27019" ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=rentafield
    command: --config /etc/mongod.conf --port 27019
    healthcheck:
      test: [ "CMD","mongosh", "--port", "27019" , "--eval", "db.adminCommand('ping')" ]

  mongoinit:
    build: .
    image: mongocustom:8.0.1
    networks: [ mongonet ]
    depends_on:
      mongo_1: { condition: service_healthy }
      mongo_2: { condition: service_healthy }
      mongo_3: { condition: service_healthy }
    command: >
      mongosh --host mongodb1:27017 --username admin --password adminpassword --authenticationDatabase admin --eval
      'rs.initiate({_id: "replica_set_single", members: [{_id: 0, host: "mongodb1:27017"}, {_id: 1, host: "mongodb2:27018"}, {_id: 2, host: "mongodb3:27019"}]});'

  kafka1:
    image: apache/kafka:3.7.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
      KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - mongonet

  kafka2:
      image: apache/kafka:3.7.0
      container_name: kafka2
      hostname: kafka2
      ports:
        - "9094:9092"
      environment:
        KAFKA_NODE_ID: 2
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:29092,EXTERNAL://localhost:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      networks:
        - mongonet

  kafka3:
      image: apache/kafka:3.7.0
      container_name: kafka3
      hostname: kafka3
      ports:
        - "9096:9092"
      environment:
        KAFKA_NODE_ID: 3
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093,3@kafka3:9093
        KAFKA_LISTENERS: CONTROLLER://:9093,INTERNAL://:29092,EXTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:29092,EXTERNAL://localhost:9096
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      networks:
        - mongonet

networks:
  mongonet: { }

volumes:
  mongo-db-data-1:
  mongo-configdb-data-1:
  mongo-db-data-2:
  mongo-configdb-data-2:
  mongo-db-data-3:
  mongo-configdb-data-3: